name: file_preview
description: A plug-in that supports flutter preview files
version: 0.0.2
homepage: https://github.com/gstory0404/file_preview

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.file_preview
        pluginClass: FilePreviewPlugin
      ios:
        pluginClass: FilePreviewPlugin
